version: '3.9'
services:
  spectrum_scraper:
      env_file: .env
      networks:
      - ergopad-net
      build:
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - ./app:/app
      restart: unless-stopped
      entrypoint: python ./app/main.py

networks:
  ergopad-net:
    driver: bridge
